### ISSUE TITLE
Link to chrome store is broken

### ISSUE THREAD

**Issue by kovetskiy** [siadat/chrome-godoc#1]
Hi, link to extension in chrome store is broken, 404 not found.

**Comment by siadat** [comment]
Hi, thank you for opening this issue. I published the extension again, the status is Pending Review. Hopefully it will be available in 24 hours.

**Comment by siadat** [comment]
@kovetskiy the chrome webstore link is up again! 
https://chrome.google.com/webstore/detail/go-doc-finder/ngfiehnpfcdmknddodaojcjpondamjcc
